version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - mto-grid-net
  chrome:
    image: selenium/node-chrome
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
      - HUB_HOST=hub
    networks:
      - mto-grid-net
  testsexecution:
     image: mto-selenium-grid
     depends_on:
        - chrome
        - hub
     volumes:
       - ./automation-results:/MTOAutomation/test-output
     networks:
       - mto-grid-net

networks:
  mto-grid-net:
    driver: bridge



